In [1]:
import numpy as np
np.seterr(all="raise")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [14]:
class WassersteinBarycenterCalculator:
    def __init__(self, gamma, epsilon, n):
        # hyperparams
        self.gamma   = gamma
        self.epsilon = epsilon
        self.n       = n
        
        # weird constants
        self.lim = 1e-20
        
        self.lambda_wave = np.zeros([n])
    
    def gradient(self, c, q):
        lam = self.lambda_wave
        gamma = self.gamma
        n = self.n
        
        return np.array( 
            [
                sum(
                    [q[j] * np.exp((-c[i, j] + lam[i]) / gamma) /
                        (sum([np.exp((-c[y, j] + lam[y]) / gamma) for y in range(n)])) 
                    for j in range(n)]
                )
            for i in range(n)]
        )
    
    def new_lambda(self, c, q):
        return self.lambda_wave - self.gamma * self.gradient(c, q)
        
    def fit(self, c, q, n_epochs=1000):
        k = 1
        
        for epoch in range(n_epochs):
            self.lambda_wave = self.new_lambda(c, q)
            print(self.lambda_wave)

In [19]:
wbc = WassersteinBarycenterCalculator(0.1, 0.1, 3)

In [20]:
c = np.ones([3, 3])
q = np.array([0.1, 0.3, 0.6])

In [21]:
wbc.fit(c, q, n_epochs=10000)

[-0.03333333 -0.03333333 -0.03333333]
[-0.06666667 -0.06666667 -0.06666667]
[-0.1 -0.1 -0.1]
[-0.13333333 -0.13333333 -0.13333333]
[-0.16666667 -0.16666667 -0.16666667]
[-0.2 -0.2 -0.2]
[-0.23333333 -0.23333333 -0.23333333]
[-0.26666667 -0.26666667 -0.26666667]
[-0.3 -0.3 -0.3]
[-0.33333333 -0.33333333 -0.33333333]
[-0.36666667 -0.36666667 -0.36666667]
[-0.4 -0.4 -0.4]
[-0.43333333 -0.43333333 -0.43333333]
[-0.46666667 -0.46666667 -0.46666667]
[-0.5 -0.5 -0.5]
[-0.53333333 -0.53333333 -0.53333333]
[-0.56666667 -0.56666667 -0.56666667]
[-0.6 -0.6 -0.6]
[-0.63333333 -0.63333333 -0.63333333]
[-0.66666667 -0.66666667 -0.66666667]
[-0.7 -0.7 -0.7]
[-0.73333333 -0.73333333 -0.73333333]
[-0.76666667 -0.76666667 -0.76666667]
[-0.8 -0.8 -0.8]
[-0.83333333 -0.83333333 -0.83333333]
[-0.86666667 -0.86666667 -0.86666667]
[-0.9 -0.9 -0.9]
[-0.93333333 -0.93333333 -0.93333333]
[-0.96666667 -0.96666667 -0.96666667]
[-1. -1. -1.]
[-1.03333333 -1.03333333 -1.03333333]
[-1.06666667 -1.06666667 -1.0666666

[-18.3 -18.3 -18.3]
[-18.33333333 -18.33333333 -18.33333333]
[-18.36666667 -18.36666667 -18.36666667]
[-18.4 -18.4 -18.4]
[-18.43333333 -18.43333333 -18.43333333]
[-18.46666667 -18.46666667 -18.46666667]
[-18.5 -18.5 -18.5]
[-18.53333333 -18.53333333 -18.53333333]
[-18.56666667 -18.56666667 -18.56666667]
[-18.6 -18.6 -18.6]
[-18.63333333 -18.63333333 -18.63333333]
[-18.66666667 -18.66666667 -18.66666667]
[-18.7 -18.7 -18.7]
[-18.73333333 -18.73333333 -18.73333333]
[-18.76666667 -18.76666667 -18.76666667]
[-18.8 -18.8 -18.8]
[-18.83333333 -18.83333333 -18.83333333]
[-18.86666667 -18.86666667 -18.86666667]
[-18.9 -18.9 -18.9]
[-18.93333333 -18.93333333 -18.93333333]
[-18.96666667 -18.96666667 -18.96666667]
[-19. -19. -19.]
[-19.03333333 -19.03333333 -19.03333333]
[-19.06666667 -19.06666667 -19.06666667]
[-19.1 -19.1 -19.1]
[-19.13333333 -19.13333333 -19.13333333]
[-19.16666667 -19.16666667 -19.16666667]
[-19.2 -19.2 -19.2]
[-19.23333333 -19.23333333 -19.23333333]
[-19.26666667 -19.266666

[-32.13333333 -32.13333333 -32.13333333]
[-32.16666667 -32.16666667 -32.16666667]
[-32.2 -32.2 -32.2]
[-32.23333333 -32.23333333 -32.23333333]
[-32.26666667 -32.26666667 -32.26666667]
[-32.3 -32.3 -32.3]
[-32.33333333 -32.33333333 -32.33333333]
[-32.36666667 -32.36666667 -32.36666667]
[-32.4 -32.4 -32.4]
[-32.43333333 -32.43333333 -32.43333333]
[-32.46666667 -32.46666667 -32.46666667]
[-32.5 -32.5 -32.5]
[-32.53333333 -32.53333333 -32.53333333]
[-32.56666667 -32.56666667 -32.56666667]
[-32.6 -32.6 -32.6]
[-32.63333333 -32.63333333 -32.63333333]
[-32.66666667 -32.66666667 -32.66666667]
[-32.7 -32.7 -32.7]
[-32.73333333 -32.73333333 -32.73333333]
[-32.76666667 -32.76666667 -32.76666667]
[-32.8 -32.8 -32.8]
[-32.83333333 -32.83333333 -32.83333333]
[-32.86666667 -32.86666667 -32.86666667]
[-32.9 -32.9 -32.9]
[-32.93333333 -32.93333333 -32.93333333]
[-32.96666667 -32.96666667 -32.96666667]
[-33. -33. -33.]
[-33.03333333 -33.03333333 -33.03333333]
[-33.06666667 -33.06666667 -33.06666667]
[-3

[-44.73333333 -44.73333333 -44.73333333]
[-44.76666667 -44.76666667 -44.76666667]
[-44.8 -44.8 -44.8]
[-44.83333333 -44.83333333 -44.83333333]
[-44.86666667 -44.86666667 -44.86666667]
[-44.9 -44.9 -44.9]
[-44.93333333 -44.93333333 -44.93333333]
[-44.96666667 -44.96666667 -44.96666667]
[-45. -45. -45.]
[-45.03333333 -45.03333333 -45.03333333]
[-45.06666667 -45.06666667 -45.06666667]
[-45.1 -45.1 -45.1]
[-45.13333333 -45.13333333 -45.13333333]
[-45.16666667 -45.16666667 -45.16666667]
[-45.2 -45.2 -45.2]
[-45.23333333 -45.23333333 -45.23333333]
[-45.26666667 -45.26666667 -45.26666667]
[-45.3 -45.3 -45.3]
[-45.33333333 -45.33333333 -45.33333333]
[-45.36666667 -45.36666667 -45.36666667]
[-45.4 -45.4 -45.4]
[-45.43333333 -45.43333333 -45.43333333]
[-45.46666667 -45.46666667 -45.46666667]
[-45.5 -45.5 -45.5]
[-45.53333333 -45.53333333 -45.53333333]
[-45.56666667 -45.56666667 -45.56666667]
[-45.6 -45.6 -45.6]
[-45.63333333 -45.63333333 -45.63333333]
[-45.66666667 -45.66666667 -45.66666667]
[-4

[-58.2 -58.2 -58.2]
[-58.23333333 -58.23333333 -58.23333333]
[-58.26666667 -58.26666667 -58.26666667]
[-58.3 -58.3 -58.3]
[-58.33333333 -58.33333333 -58.33333333]
[-58.36666667 -58.36666667 -58.36666667]
[-58.4 -58.4 -58.4]
[-58.43333333 -58.43333333 -58.43333333]
[-58.46666667 -58.46666667 -58.46666667]
[-58.5 -58.5 -58.5]
[-58.53333333 -58.53333333 -58.53333333]
[-58.56666667 -58.56666667 -58.56666667]
[-58.6 -58.6 -58.6]
[-58.63333333 -58.63333333 -58.63333333]
[-58.66666667 -58.66666667 -58.66666667]
[-58.7 -58.7 -58.7]
[-58.73333333 -58.73333333 -58.73333333]
[-58.76666667 -58.76666667 -58.76666667]
[-58.8 -58.8 -58.8]
[-58.83333333 -58.83333333 -58.83333333]
[-58.86666667 -58.86666667 -58.86666667]
[-58.9 -58.9 -58.9]
[-58.93333333 -58.93333333 -58.93333333]
[-58.96666667 -58.96666667 -58.96666667]
[-59. -59. -59.]
[-59.03333333 -59.03333333 -59.03333333]
[-59.06666667 -59.06666667 -59.06666667]
[-59.1 -59.1 -59.1]
[-59.13333333 -59.13333333 -59.13333333]
[-59.16666667 -59.166666

FloatingPointError: underflow encountered in double_scalars

In [ ]:
)