In [1]:
import numpy as np
np.seterr(all="raise")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [80]:
class WassersteinBarycenterCalculator:
    def __init__(self, gamma, epsilon, n, Q):
        # hyperparams
        self.gamma   = gamma
        self.epsilon = epsilon
        self.n       = n
        
        self.lambda_wave = np.zeros([len(Q) - 1, n])
    
    def gradient(self, c, Q, _lambda):
        gamma = self.gamma
        n = self.n
        
        return [np.array( 
            [
                sum(
                    [q[j] * np.exp((-c[i, j] + _lambda[l, i]) / gamma) /
                        (sum([np.exp((-c[y, j] + _lambda[l, y]) / gamma) for y in range(n)])) 
                    for j in range(n)]
                )
            for i in range(n)]
        ) for l, q in enumerate(Q[:-1])] +\
            [
                sum(
                    [Q[-1, j] * np.exp((-c[i, j] - np.sum(_lambda[-1])) / gamma) /
                        (sum([np.exp((-c[y, j] - np.sum(_lambda[-1])) / gamma) for y in range(n)])) 
                    for j in range(n)]
                )
            for i in range(n)]
        
    def new_lambda(self, c, Q):
        return self.lambda_wave - self.gamma *\
            self.gradient(c, Q, self.lambda_wave)
        
    def fit(self, c, Q, n_epochs=1000):
        k = 1
        
        for epoch in range(n_epochs):
            self.lambda_wave = self.new_lambda(c, Q)
            if epoch % 100 == 0: print(self.lambda_wave)

In [81]:
c = np.ones([3, 3])
q = np.array([[0.1, 0.3, 0.6], [0.5, 0.1, 0.4]])

In [82]:
wbc = WassersteinBarycenterCalculator(2.5, 0.1, 3, q)

In [83]:
wbc.fit(c, q, n_epochs=10000)

[[-1.66666667 -1.66666667 -1.66666667]]
[[-168.33333333 -168.33333333 -168.33333333]]
[[-335. -335. -335.]]
[[-501.66666667 -501.66666667 -501.66666667]]


FloatingPointError: overflow encountered in double_scalars

In [ ]:
)